# Generated by Django 5.2.8 on 2025-12-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='123456', max_length=128, null=True, verbose_name='密码'),
        ),
    ]
