# Generated by Django 5.2.8 on 2025-12-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Journal.location', verbose_name='关联地点'),
        ),
    ]
