# Generated by Django 5.2.8 on 2025-12-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0003_alter_comment_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
    ]
