# Generated by Django 5.2.8 on 2025-12-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0004_remove_comment_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='location',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
