# Generated by Django 5.2.8 on 2025-12-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0007_remove_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_photos/', verbose_name='照片')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='照片描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主图')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Journal.location', verbose_name='关联地点')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
