# Generated by Django 5.2.8 on 2025-12-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0008_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
