# Generated by Django 5.2.8 on 2025-12-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0009_remove_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
