# Generated by Django 5.2.8 on 2025-12-09 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('breed', models.CharField(max_length=100, verbose_name='品种')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('gender', models.CharField(choices=[('M', '公'), ('F', '母')], max_length=1, verbose_name='性别')),
                ('marital_status', models.CharField(choices=[('S', '单身'), ('M', '已配对'), ('P', '已生育')], max_length=1, verbose_name='婚育情况')),
                ('bio', models.TextField(verbose_name='小狗简介')),
                ('location', models.CharField(max_length=100, verbose_name='所在地市')),
                ('mbti', models.CharField(blank=True, choices=[('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ')], max_length=4, null=True, verbose_name='MBTI性格类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_profiles', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '小狗资料',
                'verbose_name_plural': '小狗资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DogAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_avatars/', verbose_name='头像图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('dog_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='friendDog.dogprofile', verbose_name='关联小狗资料')),
            ],
            options={
                'verbose_name': '小狗头像',
                'verbose_name_plural': '小狗头像',
            },
        ),
        migrations.CreateModel(
            name='DogWalkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='遛狗地点')),
                ('distance', models.FloatField(verbose_name='距离(米)')),
                ('weather', models.CharField(choices=[('SUNNY', '晴天'), ('CLOUDY', '多云'), ('RAINY', '雨天'), ('SNOWY', '雪天'), ('WINDY', '大风'), ('FOGGY', '雾天')], max_length=10, verbose_name='天气')),
                ('mood', models.CharField(choices=[('HAPPY', '开心'), ('EXCITED', '兴奋'), ('CALM', '平静'), ('TIRED', '疲惫'), ('ANXIOUS', '焦虑'), ('PLAYFUL', '活泼')], max_length=10, verbose_name='心情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('dog_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_records', to='friendDog.dogprofile', verbose_name='关联小狗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_records', to=settings.AUTH_USER_MODEL, verbose_name='记录用户')),
            ],
            options={
                'verbose_name': '遛狗记录',
                'verbose_name_plural': '遛狗记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DogWalkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='walk_photos/', verbose_name='遛狗图片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('walk_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='friendDog.dogwalkrecord', verbose_name='关联遛狗记录')),
            ],
            options={
                'verbose_name': '遛狗照片',
                'verbose_name_plural': '遛狗照片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
